### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by janislejins** [entwanne/aiorobot#1]
Hi,
I am working to setup a simple on a Mac/Python based project for a fine art research student.
We plan on using the Root as an external interface for a dance documentation project. 
We are struggling to find an API that works with python and macs without having to dive deep into BLE libraries.
Does this one already work? If so can you provide the basic install instructions?

Best,
Janis

**Comment by entwanne** [comment]
Hi,

It works but I have to release a new version to include the last features, and add some basic documentation to run it.
I'll try to do it in a few hours and I'll come back to you.

**Comment by janislejins** [comment]
Hi Entwanne/Aiorobot,
Thanks 🙏 so much!!!

**Comment by entwanne** [comment]
Ok, so all should be good to install & use this lib now!
Let's see if it's ok for you.
